CREATE TABLE IF NOT EXISTS wipe_seasons (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  server_id VARCHAR(120) NOT NULL,
  wipe_key VARCHAR(160) NOT NULL,
  started_at TIMESTAMP NULL DEFAULT NULL,
  ended_at TIMESTAMP NULL DEFAULT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  last_snapshot_at TIMESTAMP NULL DEFAULT NULL,
  snapshot_count INT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_wipe_seasons_server_key (server_id, wipe_key),
  KEY idx_wipe_seasons_active (server_id, is_active, started_at),
  KEY idx_wipe_seasons_last_snapshot (last_snapshot_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS player_wipe_stats (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  wipe_id BIGINT UNSIGNED NOT NULL,
  player_id BIGINT UNSIGNED NOT NULL,
  display_name VARCHAR(120) NOT NULL DEFAULT '',
  raw_kills INT UNSIGNED NOT NULL DEFAULT 0,
  raw_deaths INT UNSIGNED NOT NULL DEFAULT 0,
  raw_playtime_seconds INT UNSIGNED NOT NULL DEFAULT 0,
  raw_afk_seconds INT UNSIGNED NOT NULL DEFAULT 0,
  raw_reward_points INT UNSIGNED NOT NULL DEFAULT 0,
  baseline_kills INT UNSIGNED NOT NULL DEFAULT 0,
  baseline_deaths INT UNSIGNED NOT NULL DEFAULT 0,
  baseline_playtime_seconds INT UNSIGNED NOT NULL DEFAULT 0,
  baseline_afk_seconds INT UNSIGNED NOT NULL DEFAULT 0,
  kills INT UNSIGNED NOT NULL DEFAULT 0,
  deaths INT UNSIGNED NOT NULL DEFAULT 0,
  playtime_seconds INT UNSIGNED NOT NULL DEFAULT 0,
  afk_seconds INT UNSIGNED NOT NULL DEFAULT 0,
  reward_points INT UNSIGNED NOT NULL DEFAULT 0,
  kdr DECIMAL(10,3) NOT NULL DEFAULT 0,
  last_seen_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_player_wipe_stats_player (wipe_id, player_id),
  KEY idx_player_wipe_stats_kills (wipe_id, kills, deaths),
  KEY idx_player_wipe_stats_kdr (wipe_id, kdr, kills),
  KEY idx_player_wipe_stats_playtime (wipe_id, playtime_seconds),
  KEY idx_player_wipe_stats_reward_points (wipe_id, reward_points),
  KEY idx_player_wipe_stats_player_id (player_id),
  CONSTRAINT fk_player_wipe_stats_wipe FOREIGN KEY (wipe_id) REFERENCES wipe_seasons (id) ON DELETE CASCADE,
  CONSTRAINT fk_player_wipe_stats_player FOREIGN KEY (player_id) REFERENCES players (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stats_ingest_log (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  server_id VARCHAR(120) NOT NULL,
  wipe_id BIGINT UNSIGNED NULL,
  wipe_key VARCHAR(160) NOT NULL DEFAULT '',
  generated_at TIMESTAMP NULL DEFAULT NULL,
  players_received INT UNSIGNED NOT NULL DEFAULT 0,
  players_accepted INT UNSIGNED NOT NULL DEFAULT 0,
  error_count INT UNSIGNED NOT NULL DEFAULT 0,
  payload_hash CHAR(64) NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_stats_ingest_server_created (server_id, created_at),
  KEY idx_stats_ingest_wipe (wipe_id),
  CONSTRAINT fk_stats_ingest_wipe FOREIGN KEY (wipe_id) REFERENCES wipe_seasons (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
