CREATE TABLE IF NOT EXISTS support_feedback (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id VARCHAR(64) NOT NULL,
  player_id BIGINT UNSIGNED NULL,
  steam_id64 VARCHAR(32) NOT NULL DEFAULT '',
  type ENUM('bug', 'suggestion', 'feature_request') NOT NULL DEFAULT 'bug',
  status ENUM('open', 'reviewing', 'planned', 'resolved', 'closed') NOT NULL DEFAULT 'open',
  summary VARCHAR(180) NOT NULL,
  details TEXT NOT NULL,
  contact_name VARCHAR(120) NOT NULL DEFAULT '',
  contact_email VARCHAR(180) NOT NULL DEFAULT '',
  linked_display_name VARCHAR(120) NOT NULL DEFAULT '',
  page_url VARCHAR(500) NOT NULL DEFAULT '',
  browser VARCHAR(500) NOT NULL DEFAULT '',
  admin_note TEXT NULL,
  submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_support_feedback_public_id (public_id),
  KEY idx_support_feedback_status_submitted (status, submitted_at),
  KEY idx_support_feedback_type_submitted (type, submitted_at),
  KEY idx_support_feedback_player (player_id, submitted_at),
  KEY idx_support_feedback_steam_id64 (steam_id64),
  CONSTRAINT fk_support_feedback_player FOREIGN KEY (player_id) REFERENCES players (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
