CREATE TABLE IF NOT EXISTS oxide_groups (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  group_name VARCHAR(160) NOT NULL,
  title VARCHAR(160) NOT NULL DEFAULT '',
  group_rank INT NOT NULL DEFAULT 0,
  parent_group VARCHAR(160) NOT NULL DEFAULT '',
  category VARCHAR(80) NOT NULL DEFAULT 'custom',
  is_managed TINYINT(1) NOT NULL DEFAULT 0,
  is_protected TINYINT(1) NOT NULL DEFAULT 0,
  is_read_only TINYINT(1) NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 100,
  notes TEXT NULL,
  draft_revision BIGINT UNSIGNED NOT NULL DEFAULT 0,
  published_revision BIGINT UNSIGNED NOT NULL DEFAULT 0,
  published_at TIMESTAMP NULL DEFAULT NULL,
  last_seen_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_oxide_groups_name (group_name),
  KEY idx_oxide_groups_active_sort (is_active, sort_order),
  KEY idx_oxide_groups_managed (is_managed, is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS oxide_permissions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  permission_name VARCHAR(190) NOT NULL,
  plugin_name VARCHAR(120) NOT NULL DEFAULT '',
  permission_prefix VARCHAR(120) NOT NULL DEFAULT '',
  source VARCHAR(40) NOT NULL DEFAULT 'manual',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  first_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_seen_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_oxide_permissions_name (permission_name),
  KEY idx_oxide_permissions_prefix (permission_prefix),
  KEY idx_oxide_permissions_active (is_active, permission_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS oxide_group_permission_grants (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  group_id BIGINT UNSIGNED NOT NULL,
  permission_id BIGINT UNSIGNED NOT NULL,
  source VARCHAR(40) NOT NULL DEFAULT 'admin',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_oxide_group_permission_grants (group_id, permission_id),
  KEY idx_oxide_group_permission_grants_group (group_id),
  KEY idx_oxide_group_permission_grants_permission (permission_id),
  CONSTRAINT fk_oxide_group_permission_grants_group FOREIGN KEY (group_id) REFERENCES oxide_groups (id) ON DELETE CASCADE,
  CONSTRAINT fk_oxide_group_permission_grants_permission FOREIGN KEY (permission_id) REFERENCES oxide_permissions (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS oxide_group_permission_live (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  group_id BIGINT UNSIGNED NOT NULL,
  permission_id BIGINT UNSIGNED NOT NULL,
  source VARCHAR(40) NOT NULL DEFAULT 'snapshot',
  last_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_oxide_group_permission_live (group_id, permission_id),
  KEY idx_oxide_group_permission_live_group (group_id),
  KEY idx_oxide_group_permission_live_permission (permission_id),
  CONSTRAINT fk_oxide_group_permission_live_group FOREIGN KEY (group_id) REFERENCES oxide_groups (id) ON DELETE CASCADE,
  CONSTRAINT fk_oxide_group_permission_live_permission FOREIGN KEY (permission_id) REFERENCES oxide_permissions (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS oxide_permission_sync_log (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  revision BIGINT UNSIGNED NOT NULL,
  status ENUM('draft', 'pending', 'applied', 'failed', 'snapshot') NOT NULL DEFAULT 'pending',
  payload_json JSON NULL,
  payload_hash CHAR(64) NOT NULL DEFAULT '',
  message VARCHAR(500) NOT NULL DEFAULT '',
  error_text TEXT NULL,
  applied_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_oxide_permission_sync_log_revision (revision),
  KEY idx_oxide_permission_sync_log_status (status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO oxide_groups
  (group_name, title, group_rank, parent_group, category, is_managed, is_protected, is_read_only, is_active, sort_order)
VALUES
  ('default', 'default', 0, '', 'public', 1, 1, 0, 1, 10),
  ('discord', 'discord', 0, '', 'public', 1, 1, 0, 1, 20),
  ('vip_bronze', 'vip_bronze', 10, '', 'vip', 1, 0, 0, 1, 100),
  ('vip_gold', 'vip_gold', 20, 'vip_bronze', 'vip', 1, 0, 0, 1, 110),
  ('vip_elite', 'vip_elite', 30, 'vip_gold', 'vip', 1, 0, 0, 1, 120),
  ('perk_personal_mini', 'perk_personal_mini', 0, '', 'perk', 1, 0, 0, 1, 200),
  ('perk_skinbox', 'perk_skinbox', 0, '', 'perk', 1, 0, 0, 1, 210),
  ('perk_raid_kit', 'perk_raid_kit', 0, '', 'perk', 1, 0, 0, 1, 220),
  ('perk_queue_priority', 'perk_queue_priority', 0, '', 'perk', 1, 0, 0, 1, 230),
  ('perk_supporter_badge', 'perk_supporter_badge', 0, '', 'perk', 1, 0, 0, 1, 240),
  ('admin', 'admin', 1, '', 'system', 0, 1, 1, 1, 900),
  ('authenticated', 'authenticated', 0, '', 'system', 0, 1, 1, 1, 910)
ON DUPLICATE KEY UPDATE
  title = VALUES(title),
  group_rank = VALUES(group_rank),
  parent_group = VALUES(parent_group),
  category = VALUES(category),
  is_managed = VALUES(is_managed),
  is_protected = VALUES(is_protected),
  is_read_only = VALUES(is_read_only),
  is_active = VALUES(is_active),
  sort_order = VALUES(sort_order),
  updated_at = NOW();

INSERT INTO oxide_permissions
  (permission_name, plugin_name, permission_prefix, source, is_active, last_seen_at)
VALUES
  ('autodoors.use', 'AutoDoors', 'autodoors', 'seed', 1, NOW()),
  ('automaticauthorization.use', 'AutomaticAuthorization', 'automaticauthorization', 'seed', 1, NOW()),
  ('backpacks.use', 'Backpacks', 'backpacks', 'seed', 1, NOW()),
  ('backpacks.gui', 'Backpacks', 'backpacks', 'seed', 1, NOW()),
  ('backpacks.size.6', 'Backpacks', 'backpacks', 'seed', 1, NOW()),
  ('backpacks.size.12', 'Backpacks', 'backpacks', 'seed', 1, NOW()),
  ('backpacks.size.24', 'Backpacks', 'backpacks', 'seed', 1, NOW()),
  ('backpacks.size.48', 'Backpacks', 'backpacks', 'seed', 1, NOW()),
  ('backpacks.fetch', 'Backpacks', 'backpacks', 'seed', 1, NOW()),
  ('backpacks.gather', 'Backpacks', 'backpacks', 'seed', 1, NOW()),
  ('backpacks.retrieve', 'Backpacks', 'backpacks', 'seed', 1, NOW()),
  ('backpacks.keepondeath', 'Backpacks', 'backpacks', 'seed', 1, NOW()),
  ('backpacks.nofoodspoiling', 'Backpacks', 'backpacks', 'seed', 1, NOW()),
  ('bgrade.all', 'BGrade', 'bgrade', 'seed', 1, NOW()),
  ('blueprintmanager.all', 'BlueprintManager', 'blueprintmanager', 'seed', 1, NOW()),
  ('buildingskins.use', 'BuildingSkins', 'buildingskins', 'seed', 1, NOW()),
  ('buildingskins.build', 'BuildingSkins', 'buildingskins', 'seed', 1, NOW()),
  ('buildingskins.tc', 'BuildingSkins', 'buildingskins', 'seed', 1, NOW()),
  ('buildingskins.all', 'BuildingSkins', 'buildingskins', 'seed', 1, NOW()),
  ('disablewet.use', 'DisableWet', 'disablewet', 'seed', 1, NOW()),
  ('discordauth.auth', 'DiscordAuth', 'discordauth', 'seed', 1, NOW()),
  ('instantbuy.use', 'InstantBuy', 'instantbuy', 'seed', 1, NOW()),
  ('instantcraft.use', 'InstantCraft', 'instantcraft', 'seed', 1, NOW()),
  ('instantgather.use', 'InstantGather', 'instantgather', 'seed', 1, NOW()),
  ('instantsmelt.use', 'InstantSmelt', 'instantsmelt', 'seed', 1, NOW()),
  ('quicksmelt.use', 'QuickSmelt', 'quicksmelt', 'seed', 1, NOW()),
  ('randomrespawner.use', 'RandomRespawner', 'randomrespawner', 'seed', 1, NOW()),
  ('recyclerspeed.use', 'RecyclerSpeed', 'recyclerspeed', 'seed', 1, NOW()),
  ('removertool.normal', 'RemoverTool', 'removertool', 'seed', 1, NOW()),
  ('skins.use', 'Skins', 'skins', 'seed', 1, NOW()),
  ('sortbutton.use', 'SortButton', 'sortbutton', 'seed', 1, NOW()),
  ('spawnheli.minicopter.spawn', 'SpawnHeli', 'spawnheli', 'seed', 1, NOW()),
  ('spawnheli.minicopter.fetch', 'SpawnHeli', 'spawnheli', 'seed', 1, NOW()),
  ('spawnheli.minicopter.despawn', 'SpawnHeli', 'spawnheli', 'seed', 1, NOW()),
  ('powerlessturrets.use', 'PowerlessTurrets', 'powerlessturrets', 'seed', 1, NOW()),
  ('powerlessturrets.radius', 'PowerlessTurrets', 'powerlessturrets', 'seed', 1, NOW()),
  ('powerlessturrets.samradius', 'PowerlessTurrets', 'powerlessturrets', 'seed', 1, NOW()),
  ('nteleportation.home', 'NTeleportation', 'nteleportation', 'seed', 1, NOW()),
  ('nteleportation.tpr', 'NTeleportation', 'nteleportation', 'seed', 1, NOW()),
  ('nteleportation.tpb', 'NTeleportation', 'nteleportation', 'seed', 1, NOW()),
  ('nteleportation.tptown', 'NTeleportation', 'nteleportation', 'seed', 1, NOW()),
  ('nteleportation.tpoutpost', 'NTeleportation', 'nteleportation', 'seed', 1, NOW()),
  ('nteleportation.tpbandit', 'NTeleportation', 'nteleportation', 'seed', 1, NOW()),
  ('nteleportation.globalcooldownvip', 'NTeleportation', 'nteleportation', 'seed', 1, NOW()),
  ('kits.discord', 'Kits', 'kits', 'seed', 1, NOW()),
  ('kits.build', 'Kits', 'kits', 'seed', 1, NOW()),
  ('kits.cards', 'Kits', 'kits', 'seed', 1, NOW()),
  ('kits.comp', 'Kits', 'kits', 'seed', 1, NOW()),
  ('kits.medical', 'Kits', 'kits', 'seed', 1, NOW()),
  ('kits.raid', 'Kits', 'kits', 'seed', 1, NOW()),
  ('kits.scuba', 'Kits', 'kits', 'seed', 1, NOW()),
  ('serverrewards.paidpvpkit', 'ServerRewards', 'serverrewards', 'seed', 1, NOW())
ON DUPLICATE KEY UPDATE
  plugin_name = IF(plugin_name = '', VALUES(plugin_name), plugin_name),
  permission_prefix = IF(permission_prefix = '', VALUES(permission_prefix), permission_prefix),
  is_active = 1,
  last_seen_at = VALUES(last_seen_at),
  updated_at = NOW();
