CREATE TABLE IF NOT EXISTS animation_diagnostics (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  player_id BIGINT UNSIGNED NULL,
  steam_id64 VARCHAR(32) NOT NULL,
  session_hash CHAR(64) NOT NULL DEFAULT '',
  event_type VARCHAR(80) NOT NULL,
  page_id VARCHAR(80) NOT NULL DEFAULT '',
  page_url VARCHAR(700) NOT NULL DEFAULT '',
  referrer_url VARCHAR(700) NOT NULL DEFAULT '',
  viewport_width SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  viewport_height SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  device_pixel_ratio DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  reduced_motion TINYINT(1) NULL DEFAULT NULL,
  mobile_performance TINYINT(1) NULL DEFAULT NULL,
  loader_should_show TINYINT(1) NULL DEFAULT NULL,
  user_agent VARCHAR(500) NOT NULL DEFAULT '',
  details_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_animation_diagnostics_player_time (steam_id64, created_at),
  KEY idx_animation_diagnostics_session_time (session_hash, created_at),
  KEY idx_animation_diagnostics_event_time (event_type, created_at),
  KEY idx_animation_diagnostics_page_time (page_id, created_at),
  CONSTRAINT fk_animation_diagnostics_player FOREIGN KEY (player_id) REFERENCES players (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
