CREATE TABLE IF NOT EXISTS server_environment_snapshots (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  server_id VARCHAR(120) NOT NULL,
  wipe_key VARCHAR(160) NOT NULL,
  sampled_at DATETIME NOT NULL,
  rust_time DECIMAL(6,3) NOT NULL DEFAULT 0.000,
  day_fraction DECIMAL(7,6) NOT NULL DEFAULT 0.000000,
  sun_x DECIMAL(9,6) NOT NULL DEFAULT 0.000000,
  sun_y DECIMAL(9,6) NOT NULL DEFAULT 1.000000,
  sun_z DECIMAL(9,6) NOT NULL DEFAULT 0.000000,
  sun_intensity DECIMAL(7,4) NOT NULL DEFAULT 1.0000,
  sun_color VARCHAR(7) NOT NULL DEFAULT '#ffc47a',
  ambient_intensity DECIMAL(7,4) NOT NULL DEFAULT 0.3800,
  ambient_color VARCHAR(7) NOT NULL DEFAULT '#ffead2',
  cloud_coverage DECIMAL(7,4) DEFAULT NULL,
  rain_intensity DECIMAL(7,4) DEFAULT NULL,
  fog_intensity DECIMAL(7,4) DEFAULT NULL,
  payload_json JSON DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_server_environment_sample (server_id, sampled_at),
  KEY idx_server_environment_wipe_time (server_id, wipe_key, sampled_at),
  KEY idx_server_environment_sampled (sampled_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
