-- Stores authoritative current-wipe details exported by RaidlandsLeaderboards.
-- Existing player_wipe_stats rows remain the historical compatibility layer.

CREATE TABLE IF NOT EXISTS player_leaderboard_stats (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  wipe_id BIGINT UNSIGNED NOT NULL,
  player_id BIGINT UNSIGNED NOT NULL,
  total_deaths INT UNSIGNED NOT NULL DEFAULT 0,
  connections INT UNSIGNED NOT NULL DEFAULT 0,
  animal_kills INT UNSIGNED NOT NULL DEFAULT 0,
  suicides INT UNSIGNED NOT NULL DEFAULT 0,
  headshots INT UNSIGNED NOT NULL DEFAULT 0,
  melee_kills INT UNSIGNED NOT NULL DEFAULT 0,
  ranged_kills INT UNSIGNED NOT NULL DEFAULT 0,
  explosive_kills INT UNSIGNED NOT NULL DEFAULT 0,
  player_damage BIGINT UNSIGNED NOT NULL DEFAULT 0,
  npc_damage BIGINT UNSIGNED NOT NULL DEFAULT 0,
  items_crafted BIGINT UNSIGNED NOT NULL DEFAULT 0,
  structures_built INT UNSIGNED NOT NULL DEFAULT 0,
  entities_destroyed INT UNSIGNED NOT NULL DEFAULT 0,
  explosives_thrown INT UNSIGNED NOT NULL DEFAULT 0,
  shots_fired BIGINT UNSIGNED NOT NULL DEFAULT 0,
  rockets_fired INT UNSIGNED NOT NULL DEFAULT 0,
  healing_used INT UNSIGNED NOT NULL DEFAULT 0,
  distance_travelled BIGINT UNSIGNED NOT NULL DEFAULT 0,
  longest_kill_metres INT UNSIGNED NOT NULL DEFAULT 0,
  current_kill_streak INT UNSIGNED NOT NULL DEFAULT 0,
  best_kill_streak INT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_player_leaderboard_stats_player (wipe_id, player_id),
  KEY idx_player_leaderboard_headshots (wipe_id, headshots),
  KEY idx_player_leaderboard_streak (wipe_id, best_kill_streak),
  KEY idx_player_leaderboard_damage (wipe_id, player_damage),
  KEY idx_player_leaderboard_distance (wipe_id, distance_travelled),
  CONSTRAINT fk_player_leaderboard_wipe FOREIGN KEY (wipe_id) REFERENCES wipe_seasons (id) ON DELETE CASCADE,
  CONSTRAINT fk_player_leaderboard_player FOREIGN KEY (player_id) REFERENCES players (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
