<?php

return [
    [
        'id' => 0,
        'slug' => 'rank-vip',
        'name' => 'VIP',
        'product_type' => 'kit_bundle',
        'short_description' => '36-slot backpack, VIP kit, queue priority, teleport/home access, chat style, and approved conveniences.',
        'description' => 'Includes a 36-slot backpack, the server-synced VIP kit, queue priority, teleport and home access, chat and cosmetic benefits, and approved convenience permissions.',
        'oxide_group' => 'rank_vip',
        'tier_priority' => 10,
        'is_stackable' => 0,
        'is_active' => 1,
        'is_featured' => 1,
        'sort_order' => 10,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_rank-vip_week',
                'label' => 'RP Week',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 45000,
                'billing_interval' => 'one_time',
                'access_interval' => 'week',
                'access_duration_seconds' => 604800,
                'allow_auto_renew' => 1,
                'is_active' => 1,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'rank-vip-plus',
        'name' => 'VIP+',
        'product_type' => 'kit_bundle',
        'short_description' => '36-slot backpack, VIP+ kit, queue priority, faster homes and teleport, and enhanced reward benefits.',
        'description' => 'Includes a 36-slot backpack, the server-synced VIP+ kit, queue priority, faster home and teleport access, chat and cosmetic benefits, and enhanced reward permissions.',
        'oxide_group' => 'rank_vip_plus',
        'tier_priority' => 20,
        'is_stackable' => 0,
        'is_active' => 1,
        'is_featured' => 1,
        'sort_order' => 20,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_rank-vip-plus_week',
                'label' => 'RP Week',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 70000,
                'billing_interval' => 'one_time',
                'access_interval' => 'week',
                'access_duration_seconds' => 604800,
                'allow_auto_renew' => 1,
                'is_active' => 1,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'rank-mvp',
        'name' => 'MVP',
        'product_type' => 'kit_bundle',
        'short_description' => '36-slot backpack, MVP kit, queue priority, movement perks, reward benefits, and approved conveniences.',
        'description' => 'Includes a 36-slot backpack, the server-synced MVP kit, queue priority, movement perks, chat and cosmetic benefits, and approved convenience permissions.',
        'oxide_group' => 'rank_mvp',
        'tier_priority' => 30,
        'is_stackable' => 0,
        'is_active' => 1,
        'is_featured' => 1,
        'sort_order' => 30,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_rank-mvp_week',
                'label' => 'RP Week',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 90000,
                'billing_interval' => 'one_time',
                'access_interval' => 'week',
                'access_duration_seconds' => 604800,
                'allow_auto_renew' => 1,
                'is_active' => 1,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'rank-golden-vip',
        'name' => 'Golden VIP',
        'product_type' => 'kit_bundle',
        'short_description' => '42-slot backpack, Golden kit, queue priority, movement perks, and expanded rank conveniences.',
        'description' => 'Includes a 42-slot backpack, the server-synced Golden kit, queue priority, movement perks, chat and cosmetic benefits, and expanded approved conveniences.',
        'oxide_group' => 'rank_golden_vip',
        'tier_priority' => 40,
        'is_stackable' => 0,
        'is_active' => 1,
        'is_featured' => 1,
        'sort_order' => 40,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_rank-golden-vip_week',
                'label' => 'RP Week',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 130000,
                'billing_interval' => 'one_time',
                'access_interval' => 'week',
                'access_duration_seconds' => 604800,
                'allow_auto_renew' => 1,
                'is_active' => 1,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'rank-diamond-vip',
        'name' => 'Diamond VIP',
        'product_type' => 'kit_bundle',
        'short_description' => '48-slot backpack with access to the current VIP, VIP+, and Golden kit set.',
        'description' => 'Diamond has no separate active kit. It includes a 48-slot backpack and access to the current server-synced VIP, VIP+, and Golden kit set, plus Diamond rank conveniences.',
        'oxide_group' => 'rank_diamond_vip',
        'tier_priority' => 50,
        'is_stackable' => 0,
        'is_active' => 1,
        'is_featured' => 1,
        'sort_order' => 50,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_rank-diamond-vip_week',
                'label' => 'RP Week',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 250000,
                'billing_interval' => 'one_time',
                'access_interval' => 'week',
                'access_duration_seconds' => 604800,
                'allow_auto_renew' => 1,
                'is_active' => 1,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'rank-ultimate-vip',
        'name' => 'Ultimate VIP',
        'product_type' => 'kit_bundle',
        'short_description' => '48-slot backpack, Ultimate kit, vehicle and sentry access, queue priority, and rank conveniences.',
        'description' => 'Includes a 48-slot backpack, the server-synced Ultimate kit, approved vehicle and sentry access, queue priority, movement perks, and Ultimate rank conveniences.',
        'oxide_group' => 'rank_ultimate_vip',
        'tier_priority' => 60,
        'is_stackable' => 0,
        'is_active' => 1,
        'is_featured' => 1,
        'sort_order' => 60,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_rank-ultimate-vip_week',
                'label' => 'RP Week',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 400000,
                'billing_interval' => 'one_time',
                'access_interval' => 'week',
                'access_duration_seconds' => 604800,
                'allow_auto_renew' => 1,
                'is_active' => 1,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'rank-titan-vip',
        'name' => 'Titan VIP',
        'product_type' => 'kit_bundle',
        'short_description' => '48-slot backpack, Titan kit, expanded vehicle and sentry access, queue priority, and top-tier conveniences.',
        'description' => 'Includes a 48-slot backpack, the server-synced Titan kit, expanded approved vehicle and sentry access, queue priority, movement perks, and Titan rank conveniences.',
        'oxide_group' => 'rank_titan_vip',
        'tier_priority' => 70,
        'is_stackable' => 0,
        'is_active' => 1,
        'is_featured' => 1,
        'sort_order' => 70,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_rank-titan-vip_week',
                'label' => 'RP Week',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 750000,
                'billing_interval' => 'one_time',
                'access_interval' => 'week',
                'access_duration_seconds' => 604800,
                'allow_auto_renew' => 1,
                'is_active' => 1,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'perk-queue-priority',
        'name' => 'Queue Priority / Bypass',
        'product_type' => 'perk',
        'short_description' => 'Join ahead of the standard queue when the server is busy.',
        'description' => 'Applies the verified Raidlands queue-priority group to your connected Steam account.',
        'oxide_group' => 'perk_queue_priority',
        'tier_priority' => 0,
        'is_stackable' => 0,
        'is_active' => 1,
        'is_featured' => 0,
        'sort_order' => 80,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_perk-queue-priority_week',
                'label' => 'RP Week',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 8000,
                'billing_interval' => 'one_time',
                'access_interval' => 'week',
                'access_duration_seconds' => 604800,
                'allow_auto_renew' => 0,
                'is_active' => 1,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'perk-teleport-instant',
        'name' => 'Instant Teleport',
        'product_type' => 'perk',
        'short_description' => 'Use the configured priority teleport timing on your connected account.',
        'description' => 'Applies the verified priority teleport permission to your connected Steam account.',
        'oxide_group' => 'perk_teleport_instant',
        'tier_priority' => 0,
        'is_stackable' => 0,
        'is_active' => 1,
        'is_featured' => 0,
        'sort_order' => 90,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_perk-teleport-instant_week',
                'label' => 'RP Week',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 12000,
                'billing_interval' => 'one_time',
                'access_interval' => 'week',
                'access_duration_seconds' => 604800,
                'allow_auto_renew' => 0,
                'is_active' => 1,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'perk-home-5s',
        'name' => '5 Second Home Teleport',
        'product_type' => 'perk',
        'short_description' => 'Reduce the configured home teleport countdown to five seconds.',
        'description' => 'Applies the verified five-second home teleport permission to your connected Steam account.',
        'oxide_group' => 'perk_home_5s',
        'tier_priority' => 0,
        'is_stackable' => 0,
        'is_active' => 1,
        'is_featured' => 0,
        'sort_order' => 100,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_perk-home-5s_week',
                'label' => 'RP Week',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 10000,
                'billing_interval' => 'one_time',
                'access_interval' => 'week',
                'access_duration_seconds' => 604800,
                'allow_auto_renew' => 0,
                'is_active' => 1,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'perk-sign-art',
        'name' => 'Custom Sign Art /sil',
        'product_type' => 'perk',
        'short_description' => 'Use custom sign art on supported player-owned signs.',
        'description' => 'Applies the verified custom sign-art permission to your connected Steam account.',
        'oxide_group' => 'perk_sign_art',
        'tier_priority' => 0,
        'is_stackable' => 0,
        'is_active' => 1,
        'is_featured' => 0,
        'sort_order' => 110,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_perk-sign-art_week',
                'label' => 'RP Week',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 6000,
                'billing_interval' => 'one_time',
                'access_interval' => 'week',
                'access_duration_seconds' => 604800,
                'allow_auto_renew' => 0,
                'is_active' => 1,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'perk-chat-title',
        'name' => 'Custom Chat Title',
        'product_type' => 'perk',
        'short_description' => 'Display the configured Raidlands custom chat title.',
        'description' => 'Applies the custom chat-title group to your connected Steam account.',
        'oxide_group' => 'perk_chat_title',
        'tier_priority' => 0,
        'is_stackable' => 0,
        'is_active' => 1,
        'is_featured' => 0,
        'sort_order' => 120,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_perk-chat-title_week',
                'label' => 'RP Week',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 8000,
                'billing_interval' => 'one_time',
                'access_interval' => 'week',
                'access_duration_seconds' => 604800,
                'allow_auto_renew' => 0,
                'is_active' => 1,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'perk-backpack-36',
        'name' => 'Backpack Tier 1 - 36 Slots',
        'product_type' => 'perk',
        'short_description' => 'Expand the free six-slot backpack to 36 slots.',
        'description' => 'Applies a 36-slot backpack capacity to your connected Steam account. Keeping backpack contents on death is already free for everyone.',
        'oxide_group' => 'perk_backpack_36',
        'tier_priority' => 0,
        'is_stackable' => 0,
        'is_active' => 1,
        'is_featured' => 0,
        'sort_order' => 130,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_perk-backpack-36_week',
                'label' => 'RP Week',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 12000,
                'billing_interval' => 'one_time',
                'access_interval' => 'week',
                'access_duration_seconds' => 604800,
                'allow_auto_renew' => 0,
                'is_active' => 1,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'perk-backpack-42',
        'name' => 'Backpack Tier 2 - 42 Slots',
        'product_type' => 'perk',
        'short_description' => 'Expand the free six-slot backpack to 42 slots.',
        'description' => 'Applies a 42-slot backpack capacity to your connected Steam account. Keeping backpack contents on death is already free for everyone.',
        'oxide_group' => 'perk_backpack_42',
        'tier_priority' => 0,
        'is_stackable' => 0,
        'is_active' => 1,
        'is_featured' => 0,
        'sort_order' => 140,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_perk-backpack-42_week',
                'label' => 'RP Week',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 18000,
                'billing_interval' => 'one_time',
                'access_interval' => 'week',
                'access_duration_seconds' => 604800,
                'allow_auto_renew' => 0,
                'is_active' => 1,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'perk-backpack-48',
        'name' => 'Backpack Tier 3 - 48 Slots',
        'product_type' => 'perk',
        'short_description' => 'Expand the free six-slot backpack to 48 slots.',
        'description' => 'Applies a 48-slot backpack capacity to your connected Steam account. Keeping backpack contents on death is already free for everyone.',
        'oxide_group' => 'perk_backpack_48',
        'tier_priority' => 0,
        'is_stackable' => 0,
        'is_active' => 1,
        'is_featured' => 0,
        'sort_order' => 150,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_perk-backpack-48_week',
                'label' => 'RP Week',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 24000,
                'billing_interval' => 'one_time',
                'access_interval' => 'week',
                'access_duration_seconds' => 604800,
                'allow_auto_renew' => 0,
                'is_active' => 1,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'perk-backpack-keep-death',
        'name' => 'Keep Backpack on Death',
        'product_type' => 'perk',
        'short_description' => 'Legacy offer retained for purchase history; death retention is now free for everyone.',
        'description' => 'This legacy offer is no longer sold. Every player receives backpack keep-on-death by default.',
        'oxide_group' => 'perk_backpack_keep_death',
        'tier_priority' => 0,
        'is_stackable' => 0,
        'is_active' => 0,
        'is_featured' => 0,
        'sort_order' => 160,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_perk-backpack-keep-death_week',
                'label' => 'RP Week',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 25000,
                'billing_interval' => 'one_time',
                'access_interval' => 'week',
                'access_duration_seconds' => 604800,
                'allow_auto_renew' => 0,
                'is_active' => 0,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'perk-backpack-keep-wipe',
        'name' => 'Keep Backpack on Wipe',
        'product_type' => 'perk',
        'short_description' => 'Hidden while normal-wipe and force-wipe behavior is verified.',
        'description' => 'This standalone offer is not sold until its wipe behavior is verified on the live server.',
        'oxide_group' => 'perk_backpack_keep_wipe',
        'tier_priority' => 0,
        'is_stackable' => 0,
        'is_active' => 0,
        'is_featured' => 0,
        'sort_order' => 170,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_perk-backpack-keep-wipe_week',
                'label' => 'RP Week',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 40000,
                'billing_interval' => 'one_time',
                'access_interval' => 'week',
                'access_duration_seconds' => 604800,
                'allow_auto_renew' => 0,
                'is_active' => 0,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'perk-spawn-full',
        'name' => 'Spawn Full Health + Food + Water',
        'product_type' => 'perk',
        'short_description' => 'Inactive offer retained for catalogue history.',
        'description' => 'This standalone offer is not currently sold.',
        'oxide_group' => 'perk_spawn_full',
        'tier_priority' => 0,
        'is_stackable' => 0,
        'is_active' => 0,
        'is_featured' => 0,
        'sort_order' => 180,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_perk-spawn-full_week',
                'label' => 'RP Week',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 10000,
                'billing_interval' => 'one_time',
                'access_interval' => 'week',
                'access_duration_seconds' => 604800,
                'allow_auto_renew' => 0,
                'is_active' => 0,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'perk-vehicle-hp-125',
        'name' => 'Shop Vehicle HP 1.25x',
        'product_type' => 'perk',
        'short_description' => 'Shop-spawned vehicles receive the configured 1.25X health benefit.',
        'description' => 'Applies the 1.25X shop-vehicle health permission to your connected Steam account.',
        'oxide_group' => 'perk_vehicle_hp_125',
        'tier_priority' => 0,
        'is_stackable' => 0,
        'is_active' => 0,
        'is_featured' => 0,
        'sort_order' => 190,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_perk-vehicle-hp-125_week',
                'label' => 'RP Week',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 18000,
                'billing_interval' => 'one_time',
                'access_interval' => 'week',
                'access_duration_seconds' => 604800,
                'allow_auto_renew' => 0,
                'is_active' => 0,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'perk-vehicle-hp-150',
        'name' => 'Shop Vehicle HP 1.5x',
        'product_type' => 'perk',
        'short_description' => 'Shop-spawned vehicles receive the configured 1.5X health benefit.',
        'description' => 'Applies the 1.5X shop-vehicle health permission to your connected Steam account.',
        'oxide_group' => 'perk_vehicle_hp_150',
        'tier_priority' => 0,
        'is_stackable' => 0,
        'is_active' => 1,
        'is_featured' => 0,
        'sort_order' => 200,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_perk-vehicle-hp-150_week',
                'label' => 'RP Week',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 35000,
                'billing_interval' => 'one_time',
                'access_interval' => 'week',
                'access_duration_seconds' => 604800,
                'allow_auto_renew' => 0,
                'is_active' => 1,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'perk-tc-12',
        'name' => 'TC Limit 12',
        'product_type' => 'perk',
        'short_description' => 'Use up to 12 tool cupboards under the configured server limit.',
        'description' => 'Applies the verified 12-tool-cupboard limit permission to your connected Steam account.',
        'oxide_group' => 'perk_tc_12',
        'tier_priority' => 0,
        'is_stackable' => 0,
        'is_active' => 1,
        'is_featured' => 0,
        'sort_order' => 210,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_perk-tc-12_week',
                'label' => 'RP Week',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 35000,
                'billing_interval' => 'one_time',
                'access_interval' => 'week',
                'access_duration_seconds' => 604800,
                'allow_auto_renew' => 0,
                'is_active' => 1,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'perk-minicopter-instant-takeoff',
        'name' => 'Instant Minicopter Takeoff',
        'product_type' => 'perk',
        'short_description' => 'Inactive standalone offer retained for catalogue history.',
        'description' => 'This standalone offer is not currently sold.',
        'oxide_group' => 'perk_minicopter_instant_takeoff',
        'tier_priority' => 0,
        'is_stackable' => 0,
        'is_active' => 0,
        'is_featured' => 0,
        'sort_order' => 220,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_perk-minicopter-instant-takeoff_week',
                'label' => 'RP Week',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 25000,
                'billing_interval' => 'one_time',
                'access_interval' => 'week',
                'access_duration_seconds' => 604800,
                'allow_auto_renew' => 0,
                'is_active' => 0,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'perk-shop-sale-25',
        'name' => '25% Shop Sale',
        'product_type' => 'perk',
        'short_description' => 'Inactive 25% shop discount offer retained for catalogue history.',
        'description' => 'This standalone discount offer is not currently sold.',
        'oxide_group' => 'perk_shop_sale_25',
        'tier_priority' => 0,
        'is_stackable' => 0,
        'is_active' => 0,
        'is_featured' => 0,
        'sort_order' => 230,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_perk-shop-sale-25_week',
                'label' => 'RP Week',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 60000,
                'billing_interval' => 'one_time',
                'access_interval' => 'week',
                'access_duration_seconds' => 604800,
                'allow_auto_renew' => 0,
                'is_active' => 0,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'perk-shop-sale-50',
        'name' => '50% Shop Sale',
        'product_type' => 'perk',
        'short_description' => 'Inactive 50% shop discount offer retained for catalogue history.',
        'description' => 'This standalone discount offer is not currently sold.',
        'oxide_group' => 'perk_shop_sale_50',
        'tier_priority' => 0,
        'is_stackable' => 0,
        'is_active' => 0,
        'is_featured' => 0,
        'sort_order' => 240,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_perk-shop-sale-50_week',
                'label' => 'RP Week',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 140000,
                'billing_interval' => 'one_time',
                'access_interval' => 'week',
                'access_duration_seconds' => 604800,
                'allow_auto_renew' => 0,
                'is_active' => 0,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'perk-shop-sale-75',
        'name' => '75% Shop Sale',
        'product_type' => 'perk',
        'short_description' => 'Inactive 75% shop discount offer retained for catalogue history.',
        'description' => 'This standalone discount offer is not currently sold.',
        'oxide_group' => 'perk_shop_sale_75',
        'tier_priority' => 0,
        'is_stackable' => 0,
        'is_active' => 0,
        'is_featured' => 0,
        'sort_order' => 250,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_perk-shop-sale-75_week',
                'label' => 'RP Week',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 300000,
                'billing_interval' => 'one_time',
                'access_interval' => 'week',
                'access_duration_seconds' => 604800,
                'allow_auto_renew' => 0,
                'is_active' => 0,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'redeem-kit-vip',
        'name' => 'VIP Kit Redeem',
        'product_type' => 'kit_unlock',
        'short_description' => 'Inactive VIP kit unlock retained for catalogue history.',
        'description' => 'This standalone kit unlock is not currently sold.',
        'oxide_group' => '',
        'tier_priority' => 0,
        'is_stackable' => 1,
        'is_active' => 0,
        'is_featured' => 0,
        'sort_order' => 260,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_redeem-kit-vip_one_time',
                'label' => 'RP One Time',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 8000,
                'billing_interval' => 'one_time',
                'access_interval' => 'one_time',
                'access_duration_seconds' => 0,
                'allow_auto_renew' => 0,
                'is_active' => 0,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'redeem-kit-vip-plus',
        'name' => 'VIP+ Kit Redeem',
        'product_type' => 'kit_unlock',
        'short_description' => 'Inactive VIP+ kit unlock retained for catalogue history.',
        'description' => 'This standalone kit unlock is not currently sold.',
        'oxide_group' => '',
        'tier_priority' => 0,
        'is_stackable' => 1,
        'is_active' => 0,
        'is_featured' => 0,
        'sort_order' => 270,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_redeem-kit-vip-plus_one_time',
                'label' => 'RP One Time',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 12000,
                'billing_interval' => 'one_time',
                'access_interval' => 'one_time',
                'access_duration_seconds' => 0,
                'allow_auto_renew' => 0,
                'is_active' => 0,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'redeem-kit-mvp',
        'name' => 'MVP Kit Redeem',
        'product_type' => 'kit_unlock',
        'short_description' => 'Inactive MVP kit unlock retained for catalogue history.',
        'description' => 'This standalone kit unlock is not currently sold.',
        'oxide_group' => '',
        'tier_priority' => 0,
        'is_stackable' => 1,
        'is_active' => 0,
        'is_featured' => 0,
        'sort_order' => 280,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_redeem-kit-mvp_one_time',
                'label' => 'RP One Time',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 16000,
                'billing_interval' => 'one_time',
                'access_interval' => 'one_time',
                'access_duration_seconds' => 0,
                'allow_auto_renew' => 0,
                'is_active' => 0,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'redeem-kit-golden-vip',
        'name' => 'Golden VIP Kit Redeem',
        'product_type' => 'kit_unlock',
        'short_description' => 'Inactive Golden kit unlock retained for catalogue history.',
        'description' => 'This standalone kit unlock is not currently sold.',
        'oxide_group' => '',
        'tier_priority' => 0,
        'is_stackable' => 1,
        'is_active' => 0,
        'is_featured' => 0,
        'sort_order' => 290,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_redeem-kit-golden-vip_one_time',
                'label' => 'RP One Time',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 35000,
                'billing_interval' => 'one_time',
                'access_interval' => 'one_time',
                'access_duration_seconds' => 0,
                'allow_auto_renew' => 0,
                'is_active' => 0,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'redeem-kit-ultimate-vip',
        'name' => 'Ultimate VIP Kit Redeem',
        'product_type' => 'kit_unlock',
        'short_description' => 'Inactive Ultimate kit unlock retained for catalogue history.',
        'description' => 'This standalone kit unlock is not currently sold.',
        'oxide_group' => '',
        'tier_priority' => 0,
        'is_stackable' => 1,
        'is_active' => 0,
        'is_featured' => 0,
        'sort_order' => 300,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_redeem-kit-ultimate-vip_one_time',
                'label' => 'RP One Time',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 70000,
                'billing_interval' => 'one_time',
                'access_interval' => 'one_time',
                'access_duration_seconds' => 0,
                'allow_auto_renew' => 0,
                'is_active' => 0,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'redeem-kit-titan-vip',
        'name' => 'Titan VIP Kit Redeem',
        'product_type' => 'kit_unlock',
        'short_description' => 'Inactive Titan kit unlock retained for catalogue history.',
        'description' => 'This standalone kit unlock is not currently sold.',
        'oxide_group' => '',
        'tier_priority' => 0,
        'is_stackable' => 1,
        'is_active' => 0,
        'is_featured' => 0,
        'sort_order' => 310,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_redeem-kit-titan-vip_one_time',
                'label' => 'RP One Time',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 150000,
                'billing_interval' => 'one_time',
                'access_interval' => 'one_time',
                'access_duration_seconds' => 0,
                'allow_auto_renew' => 0,
                'is_active' => 0,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'redeem-pack-sentry-small',
        'name' => 'Sentry Pack Small',
        'product_type' => 'kit_unlock',
        'short_description' => 'Two defensive sentries per redemption, available once per wipe.',
        'description' => 'Redeems the server-synced small sentry pack: two auto turrets, once per wipe.',
        'oxide_group' => 'store_redeem_pack_sentry_small',
        'tier_priority' => 0,
        'is_stackable' => 1,
        'is_active' => 0,
        'is_featured' => 0,
        'sort_order' => 320,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_redeem-pack-sentry-small_one_time',
                'label' => 'RP One Time',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 10000,
                'billing_interval' => 'one_time',
                'access_interval' => 'one_time',
                'access_duration_seconds' => 0,
                'allow_auto_renew' => 0,
                'is_active' => 0,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'redeem-pack-sentry-large',
        'name' => 'Sentry Pack Large',
        'product_type' => 'kit_unlock',
        'short_description' => 'Five defensive sentries per redemption, available once per wipe.',
        'description' => 'Redeems the server-synced large sentry pack: five auto turrets, once per wipe.',
        'oxide_group' => 'store_redeem_pack_sentry_large',
        'tier_priority' => 0,
        'is_stackable' => 1,
        'is_active' => 0,
        'is_featured' => 0,
        'sort_order' => 330,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_redeem-pack-sentry-large_one_time',
                'label' => 'RP One Time',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 30000,
                'billing_interval' => 'one_time',
                'access_interval' => 'one_time',
                'access_duration_seconds' => 0,
                'allow_auto_renew' => 0,
                'is_active' => 0,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'redeem-pack-portafort',
        'name' => 'Portafort Pack',
        'product_type' => 'kit_unlock',
        'short_description' => 'Two Portafort tokens per redemption, five uses, one-hour cooldown.',
        'description' => 'Redeems two server-synced Portafort smoke tokens per use, with five uses and a one-hour cooldown.',
        'oxide_group' => 'store_redeem_pack_portafort',
        'tier_priority' => 0,
        'is_stackable' => 1,
        'is_active' => 0,
        'is_featured' => 0,
        'sort_order' => 340,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_redeem-pack-portafort_one_time',
                'label' => 'RP One Time',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 8000,
                'billing_interval' => 'one_time',
                'access_interval' => 'one_time',
                'access_duration_seconds' => 0,
                'allow_auto_renew' => 0,
                'is_active' => 0,
                'is_default' => 1,
            ],
        ],
    ],
    [
        'id' => 0,
        'slug' => 'redeem-pack-vehicle',
        'name' => 'Vehicle Pack',
        'product_type' => 'kit_unlock',
        'short_description' => 'One of each current vehicle token, available once per wipe.',
        'description' => 'Redeems one of each server-synced vehicle token: attack helicopter, scrap helicopter, balloon, RHIB, snowmobile, solo and duo submarines, and tugboat.',
        'oxide_group' => 'store_redeem_pack_vehicle',
        'tier_priority' => 0,
        'is_stackable' => 1,
        'is_active' => 0,
        'is_featured' => 0,
        'sort_order' => 350,
        'prices' => [
            [
                'id' => 0,
                'payment_method' => 'rp',
                'stripe_price_id' => 'rp_redeem-pack-vehicle_one_time',
                'label' => 'RP One Time',
                'amount_cents' => 0,
                'currency' => 'usd',
                'rp_cost' => 40000,
                'billing_interval' => 'one_time',
                'access_interval' => 'one_time',
                'access_duration_seconds' => 0,
                'allow_auto_renew' => 0,
                'is_active' => 0,
                'is_default' => 1,
            ],
        ],
    ],
];
